name: Broadcasting
abbreviation: brdc
checker: PragmaRX\Health\Checkers\Broadcasting
notify: true
column_size: 3
error_message:
  "The broadcasting service did not respond in time, it may be in trouble."
targets:
  - default:
      channel: pragmarx-health-broadcasting-channel
      route_name: pragmarx.health.broadcasting.callback
      secret: "{{ str_random(32) }}"
      timeout: 30
      routes:
        pragmarx.health.broadcasting.callback:
          uri: "/health/broadcasting/callback/{secret}"
          controller: PragmaRX\Health\Http\Controllers\Broadcasting
          action: callback
      save_to: "{{ storage_path('app') }}/broadcasting.json"
