name: S3
abbreviation: s3
checker: PragmaRX\Health\Checkers\CloudStorage
notify: true
column_size: 3
error_message: "Amazon S3 connection is failing."
targets:
  - default:
      driver: s3
      file: pragmarx-health-s3-testfile.txt
      contents: "{{ str_random(32) }}"
